CREATE SEQUENCE SEQ_ALERTAS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_ALERTA (
    alerta_id NUMBER(19, 0) DEFAULT SEQ_ALERTAS.NEXTVAL NOT NULL,
    equipamento_id NUMBER(19, 0) NOT NULL,
    data_hora TIMESTAMP(6) NOT NULL,
    nivel VARCHAR2(255 CHAR) CHECK (nivel in ('BAIXO', 'MEDIO', 'ALTO')),
    PRIMARY KEY (alerta_id)
);

CREATE SEQUENCE SEQ_EQUIPAMENTOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_EQUIPAMENTO (
    equipamento_id NUMBER(19, 0) DEFAULT SEQ_EQUIPAMENTOS.NEXTVAL NOT NULL,
    usuario_id NUMBER(19, 0) NOT NULL,
    consumo_medio_kw FLOAT(53) NOT NULL,
    localizacao VARCHAR2(255 CHAR),
    nome VARCHAR2(255 CHAR),
    PRIMARY KEY (equipamento_id)
);

CREATE SEQUENCE SEQ_LEITURAS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_LEITURA (
    leitura_id NUMBER(19, 0) DEFAULT SEQ_LEITURAS.NEXTVAL NOT NULL,
    sensor_id NUMBER(19, 0) NOT NULL,
    consumo_kw FLOAT(53) NOT NULL,
    data_hora TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (leitura_id)
);

CREATE SEQUENCE SEQ_SENSORES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_SENSOR (
    sensor_id NUMBER(19, 0) DEFAULT SEQ_SENSORES.NEXTVAL NOT NULL,
    equipamento_id NUMBER(19, 0) NOT NULL,
    ativo NUMBER(1, 0) CHECK (ativo in (0, 1)),
    codigo_serial VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    tipo VARCHAR2(255 CHAR),
    PRIMARY KEY (sensor_id)
);

CREATE SEQUENCE SEQ_USUARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_USUARIO (
    usuario_id NUMBER(19, 0) DEFAULT SEQ_USUARIOS.NEXTVAL NOT NULL,
    email VARCHAR2(255 CHAR) NOT NULL,
    nome VARCHAR2(255 CHAR) NOT NULL,
    role VARCHAR2(255 CHAR) CHECK (role IN ('ADMIN', 'USER')),
    senha VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (usuario_id)
);

ALTER TABLE T_ALERTA
    ADD CONSTRAINT FK_ALERTA_EQUIPAMENTO
        FOREIGN KEY (EQUIPAMENTO_ID)
            REFERENCES T_EQUIPAMENTO;

ALTER TABLE T_EQUIPAMENTO
    ADD CONSTRAINT FK_EQUIPAMENTO_USUARIO
        FOREIGN KEY (USUARIO_ID)
            REFERENCES T_USUARIO;

ALTER TABLE T_LEITURA
    ADD CONSTRAINT FK_LEITURA_SENSOR
        FOREIGN KEY (SENSOR_ID)
            REFERENCES T_SENSOR;

ALTER TABLE T_SENSOR
    ADD CONSTRAINT FK_SENSOR_EQUIPAMENTO
        FOREIGN KEY (EQUIPAMENTO_ID)
            REFERENCES T_EQUIPAMENTO;
