ALTER TABLE T_ALERTA
    ADD CONSTRAINT FK_ALERTA_EQUIPAMENTO
    FOREIGN KEY (EQUIPAMENTO_ID)
    REFERENCES T_EQUIPAMENTO;

ALTER TABLE T_EQUIPAMENTO
    ADD CONSTRAINT FK_EQUIPAMENTO_USUARIO
    FOREIGN KEY (USUARIO_ID)
    REFERENCES T_USUARIO;

ALTER TABLE T_LEITURA
    ADD CONSTRAINT FK_LEITURA_SENSOR
    FOREIGN KEY (SENSOR_ID)
    REFERENCES T_SENSOR;

ALTER TABLE T_SENSOR
    ADD CONSTRAINT FK_SENSOR_EQUIPAMENTO
    FOREIGN KEY (EQUIPAMENTO_ID)
    REFERENCES T_EQUIPAMENTO;